# Modules
- color: "fbca04"
  description: "This issue or pull request is related to enterprise-organization module."
  name: ":floppy_disk: enterprise-organization"
- color: "fbca04"
  description: "This issue or pull request is related to org-organization module."
  name: ":floppy_disk: org-organization"
- color: "fbca04"
  description: "This issue or pull request is related to org-team module."
  name: ":floppy_disk: org-team"
- color: "fbca04"
  description: "This issue or pull request is related to project module."
  name: ":floppy_disk: project"
- color: "fbca04"
  description: "This issue or pull request is related to repository module."
  name: ":floppy_disk: repository"
- color: "fbca04"
  description: "This issue or pull request is related to webhook module."
  name: ":floppy_disk: webhook"
